//
//@author Alorse
//@version=4
study(title="TTM Squeeze [Alorse]")
length = input(title="Length", type=input.integer, defval=20, minval=0)
SP = input(title="Short Stop Loss (%)", type=input.float, minval=0.0, step=0.1, defval=10) * 0.01
bband(length, mult) =>
	sma(close, length) + mult * stdev(close, length)
keltner(length, mult) =>
	ema(close, length) + mult * ema(tr, length)

e1 = (highest(high, length) + lowest(low, length)) / 2 + sma(close, length)
osc = linreg(close - e1 / 2, length, 0)
diff = bband(length, 2) - keltner(length, 1)
osc_color = osc[1] < osc[0] ? osc[0] >= 0 ? color.lime : color.maroon : osc[0] >= 0 ? color.green : color.red
mid_color = diff >= 0 ? color.white : color.black

plot(osc, color=osc_color, style=plot.style_area, linewidth=1)
plot(0, color=mid_color, style=plot.style_circles, linewidth=1)
