//@version=4
// strategy(title="TTM Squeeze Alorse", overlay=true, pyramiding=0, currency=currency.USD, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
study(title="TTM Squeeze Alorse", overlay=true)
length = input(title="Length", type=input.integer, defval=20, minval=0)
SP = input(title="Short Stop Loss (%)", type=input.float, minval=0.0, step=0.1, defval=10) * 0.01
bband(length, mult) =>
	sma(close, length) + mult * stdev(close, length)
keltner(length, mult) =>
	ema(close, length) + mult * ema(tr, length)

e1 = (highest(high, length) + lowest(low, length)) / 2 + sma(close, length)
osc = linreg(close - e1 / 2, length, 0)
diff = bband(length, 2) - keltner(length, 1)
// 1 = cold: price > 0
// 2 = hot: price < 0 Sell
// 3 = hot: price < Buy
// 4 = cold: price > 0
osc_status = osc[1] < osc[0] ? osc[0] >= 0 ? 1 : 3 : osc[0] >= 0 ? 2 : 4
osc_color = osc[1] < osc[0] ? osc[0] >= 0 ? color.lime : color.maroon : osc[0] >= 0 ? color.green : color.red
mid_color = diff >= 0 ? color.white : color.black


plot(osc, color=osc_color, style=plot.style_area, linewidth=1)
plot(0, color=mid_color, style=plot.style_circles, linewidth=1)


// sell1 = osc[0] > osc[1] ? osc[0] >= 0 ? false : false : osc[0] >= 0 ? true : false
// buy1 = osc[0] > osc[1] ? osc[0] >= 0 ? false : true : osc[0] >= 0 ? false : false
// strategy.entry("Long", true, when=buy1)
// strategy.close("Long", when=sell1)

// longStopPrice  = strategy.position_avg_price * (1 - SP)
// if (strategy.position_size > 0)
//     strategy.exit(id="Exit", stop=longStopPrice)